config/routes.rb
Tonez::Application.routes.draw do
  resources :molecules

  resources :atoms

  resources :things

  root :to=>"home#index" 

end

app/models/atom.rb
class Atom < ActiveRecord::Base
  belongs_to :molecule , :inverse_of=>:atoms
end

app/models/molecule.rb
class Molecule < ActiveRecord::Base
  has_many :atoms , :inverse_of=>:molecule
end

app/models/parent.rb
class Parent < ActiveRecord::Base
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  belongs_to :parent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/atoms_controller.rb
class AtomsController < ApplicationController
  before_action :set_atom, only: [:show, :edit, :update, :destroy]

  # GET /atoms
  # GET /atoms.json
  def index
    @atoms = Atom.all
  end

  # GET /atoms/1
  # GET /atoms/1.json
  def show
  end

  # GET /atoms/new
  def new
    @atom = Atom.new
  end

  # GET /atoms/1/edit
  def edit
  end

  # POST /atoms
  # POST /atoms.json
  def create
    @atom = Atom.new(atom_params)

    respond_to do |format|
      if @atom.save
        format.html { redirect_to @atom, notice: 'Atom was successfully created.' }
        format.json { render action: 'show', status: :created, location: @atom }
      else
        format.html { render action: 'new' }
        format.json { render json: @atom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atoms/1
  # PATCH/PUT /atoms/1.json
  def update
    respond_to do |format|
      if @atom.update(atom_params)
        format.html { redirect_to @atom, notice: 'Atom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @atom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atoms/1
  # DELETE /atoms/1.json
  def destroy
    @atom.destroy
    respond_to do |format|
      format.html { redirect_to atoms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atom
      @atom = Atom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atom_params
      params[:atom]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #app root 
  def index
    
  end 
end

app/controllers/molecules_controller.rb
class MoleculesController < ApplicationController
  before_action :set_molecule, only: [:show, :edit, :update, :destroy]

  # GET /molecules
  # GET /molecules.json
  def index
    @molecules = Molecule.all
    respond_to do |format|
      format.html { redirect_to @molecule, notice: 'Molecule was successfully created.' }
      # format.json { render :json=>{ :molecules=>@molecules, :atoms=>Atom.all.to_a },  status: 200 }
      format.json { render :json=> @molecules ,  status: 200 }
      # format.json { render :text=>%Q| {"molecules":[{"id":1,"molecular_weight":"781.0","name":"textothoriumine","created_at":"2013-12-26T15:05:49.436Z","updated_at":"2013-12-26T15:05:49.436Z", "atoms":[26] }] , "atoms":[{"id": 26} ] } | ,  status: 200 }
    end
    
  end

  # GET /molecules/1
  # GET /molecules/1.json
  def show
    edit
    return
  end

  # GET /molecules/new
  def new
    @molecule = Molecule.new
  end

  # GET /molecules/1/edit
  def edit
    # format.json { render :json=>{ :molecule=>@molecule, :atoms=>@molecules.atoms },  status: 200 }
    @molecule=Molecule.find params[:id] 
    respond_to do |format|
      format.json { render :json=> @molecule ,  status: 200 }
    end
  end

  # POST /molecules
  # POST /molecules.json
  def create
    @molecule = Molecule.new(molecule_params)

    respond_to do |format|
      if @molecule.save
        format.html { redirect_to @molecule, notice: 'Molecule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @molecule }
      else
        format.html { render action: 'new' }
        format.json { render json: @molecule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /molecules/1
  # PATCH/PUT /molecules/1.json
  def update
    respond_to do |format|
      if @molecule.update(molecule_params)
        format.html { redirect_to @molecule, notice: 'Molecule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @molecule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /molecules/1
  # DELETE /molecules/1.json
  def destroy
    @molecule.destroy
    respond_to do |format|
      format.html { redirect_to molecules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_molecule
      @molecule = Molecule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def molecule_params
      params[:molecule]
    end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @thing }
      else
        format.html { render action: 'new' }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params[:thing]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atoms_helper.rb
module AtomsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/molecules_helper.rb
module MoleculesHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/atoms/_form.html.erb
<%= form_for(@atom) do |f| %>
  <% if @atom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atom.errors.count, "error") %> prohibited this atom from being saved:</h2>

      <ul>
      <% @atom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atoms/edit.html.erb
<h1>Editing atom</h1>

<%= render 'form' %>

<%= link_to 'Show', @atom %> |
<%= link_to 'Back', atoms_path %>

app/views/atoms/index.html.erb
<h1>Listing atoms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atoms.each do |atom| %>
      <tr>
        <td><%= link_to 'Show', atom %></td>
        <td><%= link_to 'Edit', edit_atom_path(atom) %></td>
        <td><%= link_to 'Destroy', atom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Atom', new_atom_path %>

app/views/atoms/new.html.erb
<h1>New atom</h1>

<%= render 'form' %>

<%= link_to 'Back', atoms_path %>

app/views/atoms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_atom_path(@atom) %> |
<%= link_to 'Back', atoms_path %>

app/views/home/index.html.erb
Tonez

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tonez</title>
  <%= stylesheet_link_tag    "application", media: "all"  %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/molecules/_form.html.erb
<%= form_for(@molecule) do |f| %>
  <% if @molecule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@molecule.errors.count, "error") %> prohibited this molecule from being saved:</h2>

      <ul>
      <% @molecule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/molecules/edit.html.erb
<h1>Editing molecule</h1>

<%= render 'form' %>

<%= link_to 'Show', @molecule %> |
<%= link_to 'Back', molecules_path %>

app/views/molecules/index.html.erb
<h1>Listing molecules</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @molecules.each do |molecule| %>
      <tr>
        <td><%= link_to 'Show', molecule %></td>
        <td><%= link_to 'Edit', edit_molecule_path(molecule) %></td>
        <td><%= link_to 'Destroy', molecule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Molecule', new_molecule_path %>

app/views/molecules/new.html.erb
<h1>New molecule</h1>

<%= render 'form' %>

<%= link_to 'Back', molecules_path %>

app/views/molecules/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_molecule_path(@molecule) %> |
<%= link_to 'Back', molecules_path %>

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<h1>Listing things</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thing', new_thing_path %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>